config/routes.rb
Phonesurvey::Application.routes.draw do

  authenticated :user do
    root :to => 'products#index'
  end

  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]

  resources :products do
    resources :surveys do
      resources :feedbacks
    end
  end
  mount TropoApp, :at => "/tropo"
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  validates :question, :presence => true
  validates :yes_no, :presence => true

  belongs_to :product
  has_many :feedbacks
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_product
  before_filter :find_survey, :only => [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = @product.surveys.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @surveys }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @feedbacks = @survey.feedbacks.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/new
  # GET /surveys/new.json
  def new
    @survey = @product.surveys.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = @product.surveys.build(params[:survey])
    
    respond_to do |format|
      if @survey.save
        format.html { redirect_to [@product, @survey], notice: 'Survey was successfully created.' }
        format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /surveys/1
  # PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        format.html { redirect_to [@product, @survey], notice: 'Survey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to product_surveys_path(@product) }
      format.json { head :no_content }
    end
  end

  private
    def find_product
      @product = Product.find(params[:product_id])
    end

    def find_survey
      @survey = Survey.find(params[:id])
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= simple_form_for([@product, @survey]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :question %>
    <%= f.input :yes_no %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing survey</h1>

<%= render 'form' %>

<%= link_to 'Show', product_survey_path(@product, @survey) %> |
<%= link_to 'Back', product_surveys_path(@product) %>

app/views/surveys/index.html.erb
<h1><%= link_to @product.name, @product %> &raquo Listing surveys</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Question</th>
      <th>Yes no</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.question %></td>
        <td><%= survey.yes_no %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.show")),
                        product_survey_path(@product, survey), :class => 'btn btn-mini' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_product_survey_path(@product, survey), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      [@product, survey],
                      :method => :delete,
                      :confirm => t('.confirm',
                                  :default => t("helpers.links.confirm",
                                  :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back to product")),
              product_path(@product), :class => 'btn'  %>
  <% if @product.surveys.size < 3 %>
    <%= link_to t('.new', :default => t("helpers.links.new survey")),
                new_product_survey_path(@product),
                :class => 'btn btn-primary' %>
  <% end %>
</div>

app/views/surveys/new.html.erb
<h1><%= @product.name %> &raquo New survey</h1>

<%= render 'form' %>

<%= link_to 'Back', product_surveys_path(@product) %>

app/views/surveys/show.html.erb
<h1><%= link_to @product.name, @product %> &raquo Survey</h1>

<p>
  <b>Question:</b>
  <%= @survey.question %>
</p>

<p>
  <b>Yes no:</b>
  <%= @survey.yes_no %>
</p>

<h3>Listing feedbacks</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Survey</th>
      <th>Answer</th>
      <th>Callerid</th>
    </tr>
  </thead>
  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.survey_id %></td>
        <td><%= feedback.answer %></td>
        <td><%= feedback.callerid %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back to product")),
              product_path(@product), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit survey")),
              edit_product_survey_path(@product), :class => 'btn'  %>
  <%= link_to t('.destroy', :default => t("helpers.links.delete")),
              [@product, @survey],
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>