config/routes.rb
Phonesurvey::Application.routes.draw do

  authenticated :user do
    root :to => 'products#index'
  end

  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]

  resources :products do
    resources :surveys do
      resources :feedbacks
    end
  end
  mount TropoApp, :at => "/tropo"
end

app/views/layouts/_navigation.html.erb
<%= link_to "PhoneSurvey", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to('Products', products_path) %>        
    </li>
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to('Admin', users_path) %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PhoneSurvey" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <% flash.each do |name, msg| %>
                <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                  <a class="close" data-dismiss="alert">×</a>
                  <%= msg %>
                </div>
              <% end %>
              <%= yield %>
            </div>
          </div>
          <footer>
          <p> created by Julius Francisco baldrailers at gmail dot com. Powered by TROPO </p>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>